// <auto-generated />
using CrudTest2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudTest2.Migrations
{
    [DbContext(typeof(KlientiContext))]
    partial class KlientiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrudTest2.Models.KlientiDatabase", b =>
                {
                    b.Property<int>("KlientiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlientiID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumriKlientave")
                        .HasColumnType("int");

                    b.Property<string>("NumriTelefonit")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Qyteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Shteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ZipCodi")
                        .HasColumnType("int");

                    b.HasKey("KlientiID");

                    b.ToTable("Klienti");
                });
#pragma warning restore 612, 618
        }
    }
}
